/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.airlift.bytecode;

import com.google.common.base.CharMatcher;
import com.sun.management.HotSpotDiagnosticMXBean;
import org.objectweb.asm.commons.CodeSizeEvaluator;

import java.io.StringWriter;
import java.lang.invoke.MethodHandles.Lookup;
import java.lang.management.ManagementFactory;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import static io.airlift.bytecode.ParameterizedType.typeFromJavaClassName;

public final class BytecodeUtils
{
    private static final AtomicLong CLASS_ID = new AtomicLong();

    // DontCompileHugeMethods is a product flag and can be read from the runtime.
    private static final boolean DONT_COMPILE_HUGE_METHODS = getVmOption("DontCompileHugeMethods")
            .map(Boolean::parseBoolean)
            .orElse(true);

    // HugeMethodLimit is a develop flag, only readable on debug JVM builds; on
    // release builds it is compiled in as the constant 8000.
    private static final int HUGE_METHOD_LIMIT = getVmOption("HugeMethodLimit")
            .map(Integer::parseInt)
            .orElse(8000);

    private static final int MAX_INLINE_SIZE = getVmOption("MaxInlineSize")
            .map(Integer::parseInt)
            .orElse(35);

    private static final int FREQ_INLINE_SIZE = getVmOption("FreqInlineSize")
            .map(Integer::parseInt)
            .orElse(325);

    // hard JVM limit on the size of the code attribute of a method (JVMS 4.7.3)
    private static final int MAX_METHOD_SIZE = 65535;

    private BytecodeUtils() {}

    public static ParameterizedType uniqueClassName(String basePackage, String baseName)
    {
        String className = toJavaIdentifierString(baseName) + "_" + CLASS_ID.incrementAndGet();
        return typeFromJavaClassName(basePackage + ".$gen." + className);
    }

    public static ParameterizedType uniqueClassName(Lookup lookup, String baseName)
    {
        // hidden classed require the class to be in the lookup package
        String basePackage = lookup.lookupClass().getPackage().getName();
        String className = toJavaIdentifierString(baseName) + "_" + CLASS_ID.incrementAndGet();
        return typeFromJavaClassName(basePackage + "." + className);
    }

    public static String toJavaIdentifierString(String className)
    {
        // replace invalid characters with '_'
        return CharMatcher.forPredicate(Character::isJavaIdentifierPart).negate()
                .replaceFrom(className, '_');
    }

    public static String dumpBytecodeTree(ClassDefinition classDefinition)
    {
        StringWriter writer = new StringWriter();
        new DumpBytecodeVisitor(writer).visitClass(classDefinition);
        return writer.toString();
    }

    /**
     * Estimates the size in bytes of the code generated by the given node.
     * The returned value is an upper bound: instructions whose final encoding
     * depends on jump offsets or constant pool layout are counted at their
     * widest form. Useful for checking generated methods against the JVM
     * limit of 65535 bytes per method.
     */
    public static int estimateMaxCodeSize(BytecodeNode node, Scope scope)
    {
        CodeSizeEvaluator evaluator = new CodeSizeEvaluator(null);
        MethodGenerationContext context = new MethodGenerationContext(evaluator);
        context.enterScope(scope);
        node.accept(evaluator, context);
        context.exitScope(scope);
        return evaluator.getMaxSize();
    }

    /**
     * Checks whether a method generated from the given node is eligible for JIT
     * compilation on this JVM. On HotSpot with default flags, methods whose code
     * attribute exceeds {@code -XX:HugeMethodLimit} (8000 bytes) are never JIT
     * compiled and always run interpreted; the limits are read from the runtime
     * where available. Since the size estimate is an upper bound, a {@code true}
     * result is a guarantee; a {@code false} result may be a false negative for
     * code close to the limit.
     */
    public static boolean isJitCompilable(BytecodeNode node, Scope scope)
    {
        return !DONT_COMPILE_HUGE_METHODS || estimateMaxCodeSize(node, scope) <= HUGE_METHOD_LIMIT;
    }

    /**
     * Checks whether the code generated by the given node fits the hard JVM limit
     * of 65535 bytes for the code attribute of a method (JVMS 4.7.3). A method
     * exceeding the limit fails at class generation time. Since the size estimate
     * is an upper bound, a {@code true} result is a guarantee; a {@code false}
     * result may be a false negative for code close to the limit.
     */
    public static boolean fitsMethodSizeLimit(BytecodeNode node, Scope scope)
    {
        return estimateMaxCodeSize(node, scope) <= MAX_METHOD_SIZE;
    }

    /**
     * Checks whether a method generated from the given node is small enough for the
     * HotSpot JIT to inline into an ordinary (not hot) call site, as controlled by
     * {@code -XX:MaxInlineSize} (35 bytes by default); the limit is read from the
     * runtime where available. Since the size estimate is an upper bound, a
     * {@code true} result is a guarantee; a {@code false} result may be a false
     * negative for code close to the limit.
     */
    public static boolean isInlineable(BytecodeNode node, Scope scope)
    {
        return estimateMaxCodeSize(node, scope) <= MAX_INLINE_SIZE;
    }

    /**
     * Checks whether a method generated from the given node is small enough for the
     * HotSpot JIT to inline into a hot call site, as controlled by
     * {@code -XX:FreqInlineSize} (325 bytes by default); the limit is read from the
     * runtime where available. Since the size estimate is an upper bound, a
     * {@code true} result is a guarantee; a {@code false} result may be a false
     * negative for code close to the limit.
     */
    public static boolean isInlineableWhenHot(BytecodeNode node, Scope scope)
    {
        return estimateMaxCodeSize(node, scope) <= FREQ_INLINE_SIZE;
    }

    private static Optional<String> getVmOption(String name)
    {
        try {
            HotSpotDiagnosticMXBean diagnostics = ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class);
            if (diagnostics == null) {
                return Optional.empty();
            }
            return Optional.of(diagnostics.getVMOption(name).getValue());
        }
        catch (RuntimeException | LinkageError e) {
            // not a HotSpot JVM, or the option does not exist in this build
            return Optional.empty();
        }
    }
}
